version: '2'
services:
  jekyll:
    network_mode: bridge
    image: "jekyll/jekyll:3.6.2"
    command: "jekyll server"
    environment:
      - JEKYLL_ENV=production
    volumes:
      - "$PWD/test/test-site:/srv/jekyll"
    labels:
      - "traefik.frontend.rule=Host:testme.io"
      - "traefik.enable=true"
    depends_on:
      - "reverse-proxy"
  # Our reverse proxy
  reverse-proxy:
    network_mode: bridge
    image: "traefik:1.3.8"
    command: "--debug --defaultentrypoints=http --entrypoints=Name:http Address::80 --docker --docker.watch --docker.exposedbydefault=false"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - "80:80"